language: java

jdk:
- openjdk8
- openjdk11

os:
- linux

dist: xenial

cache:
  directories:
  - $HOME/.m2

install:
- mvn --batch-mode --show-version clean install -P quick

script:
- mvn --batch-mode --show-version clean verify
