name: Build
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: adopt
        cache: maven
    - run: mvn --batch-mode --show-version clean verify
